/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Statistik.java
 *
 * Created on Mar 8, 2011, 10:03:18 AM
 */

package go.gui;

import javax.swing.event.*;
import javax.swing.table.TableColumn;

import java.awt.event.*;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import go.StatistikException;

/**
 *
 * @author sopr052
 */
public class Statistik extends javax.swing.JPanel implements ChangeListener, ActionListener{

	go.Statistik daten = null;
	
    /** Creates new form Statistik */
    public Statistik(Main main) {
        initComponents(main);
        pnlTab.addChangeListener(this);
        lade();
        stateChanged(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents(Main main) {

    	 pnlTab = new javax.swing.JTabbedPane();
         pnlSpiele = new javax.swing.JPanel();
         scrSpiele = new javax.swing.JScrollPane();
         tblSpiele = new javax.swing.JTable();
         lblSpiele = new javax.swing.JLabel();
         pnlSiege = new javax.swing.JPanel();
         scrSiege = new javax.swing.JScrollPane();
         tblSiege = new javax.swing.JTable();
         lblSiege = new javax.swing.JLabel();
         pnlGewonnen = new javax.swing.JPanel();
         scrGewonnen = new javax.swing.JScrollPane();
         tblGewonnen = new javax.swing.JTable();
         lblGewonnen = new javax.swing.JLabel();
         pnlAufgegeben = new javax.swing.JPanel();
         scrAufgegeben = new javax.swing.JScrollPane();
         tblAufgegeben = new javax.swing.JTable();
         lblAufgegeben = new javax.swing.JLabel();
         btnZuruecksetzen = new javax.swing.JButton();
         lblTitel = new javax.swing.JLabel();
         btnZurueck = new javax.swing.JButton();

         setName("Form"); // NOI18N

         pnlTab.setName("pnlTab"); // NOI18N

         pnlSpiele.setName("pnlSpiele"); // NOI18N

         scrSpiele.setName("scrSpiele"); // NOI18N

         tblSpiele.setModel(new javax.swing.table.DefaultTableModel(
                 new Object [][] {
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null}
                 },
                 new String [] {
                     "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
                 }
             ));
             tblSpiele.setName("tblSpiele"); // NOI18N
             scrSpiele.setViewportView(tblSpiele);

             lblSpiele.setIcon(new javax.swing.ImageIcon("img/Statistikueberschrift.png"));
             lblSpiele.setText(""); // NOI18N

             javax.swing.GroupLayout pnlSpieleLayout = new javax.swing.GroupLayout(pnlSpiele);
             pnlSpiele.setLayout(pnlSpieleLayout);
             pnlSpieleLayout.setHorizontalGroup(
                 pnlSpieleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                 .addGroup(pnlSpieleLayout.createSequentialGroup()
                     .addContainerGap()
                     .addGroup(pnlSpieleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                         .addComponent(scrSpiele, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                         .addComponent(lblSpiele))
                     .addContainerGap())
             );
             pnlSpieleLayout.setVerticalGroup(
                 pnlSpieleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                 .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSpieleLayout.createSequentialGroup()
                     .addContainerGap()
                     .addComponent(lblSpiele)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(scrSpiele, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addContainerGap())
             );

             pnlTab.addTab("Spiele", pnlSpiele); // NOI18N

             pnlSiege.setName("pnlSiege"); // NOI18N

             scrSiege.setName("scrSiege"); // NOI18N

             tblSiege.setModel(new javax.swing.table.DefaultTableModel(
                 new Object [][] {
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null}
                 },
                 new String [] {
                     "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
                 }
             ));
             tblSiege.setName("tblSiege"); // NOI18N
             scrSiege.setViewportView(tblSiege);

             lblSiege.setIcon(new javax.swing.ImageIcon("img/Statistikueberschrift.png"));

             javax.swing.GroupLayout pnlSiegeLayout = new javax.swing.GroupLayout(pnlSiege);
             pnlSiege.setLayout(pnlSiegeLayout);
             pnlSiegeLayout.setHorizontalGroup(
                 pnlSiegeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                 .addGroup(pnlSiegeLayout.createSequentialGroup()
                     .addContainerGap()
                     .addGroup(pnlSiegeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                         .addComponent(scrSiege, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                         .addComponent(lblSiege))
                     .addContainerGap())
             );
             pnlSiegeLayout.setVerticalGroup(
                 pnlSiegeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                 .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSiegeLayout.createSequentialGroup()
                     .addContainerGap()
                     .addComponent(lblSiege)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(scrSiege, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addContainerGap())
             );

             pnlTab.addTab("Siege", pnlSiege); // NOI18N

             pnlGewonnen.setName("pnlGewonnen"); // NOI18N

             scrGewonnen.setName("scrGewonnen"); // NOI18N

             tblGewonnen.setModel(new javax.swing.table.DefaultTableModel(
                 new Object [][] {
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null}
                 },
                 new String [] {
                     "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
                 }
             ));
             tblGewonnen.setName("tblGewonnen"); // NOI18N
             scrGewonnen.setViewportView(tblGewonnen);

             lblGewonnen.setIcon(new javax.swing.ImageIcon("img/Statistikueberschrift.png"));
             lblGewonnen.setName("lblGewonnen"); // NOI18N

             javax.swing.GroupLayout pnlGewonnenLayout = new javax.swing.GroupLayout(pnlGewonnen);
             pnlGewonnen.setLayout(pnlGewonnenLayout);
             pnlGewonnenLayout.setHorizontalGroup(
                 pnlGewonnenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                 .addGroup(pnlGewonnenLayout.createSequentialGroup()
                     .addContainerGap()
                     .addGroup(pnlGewonnenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                         .addComponent(scrGewonnen, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                         .addComponent(lblGewonnen))
                     .addContainerGap())
             );
             pnlGewonnenLayout.setVerticalGroup(
                 pnlGewonnenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                 .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlGewonnenLayout.createSequentialGroup()
                     .addContainerGap()
                     .addComponent(lblGewonnen)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(scrGewonnen, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addContainerGap())
             );

             pnlTab.addTab("Gewonnen", pnlGewonnen); // NOI18N

             pnlAufgegeben.setName("pnlAufgegeben"); // NOI18N

             scrAufgegeben.setName("scrAufgegeben"); // NOI18N

             tblAufgegeben.setModel(new javax.swing.table.DefaultTableModel(
                 new Object [][] {
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null},
                     {null, null, null, null, null, null, null, null}
                 },
                 new String [] {
                     "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
                 }
             ));
             tblAufgegeben.setName("tblAufgegeben"); // NOI18N
             scrAufgegeben.setViewportView(tblAufgegeben);

             lblAufgegeben.setIcon(new javax.swing.ImageIcon("img/Statistikueberschrift.png"));

             javax.swing.GroupLayout pnlAufgegebenLayout = new javax.swing.GroupLayout(pnlAufgegeben);
             pnlAufgegeben.setLayout(pnlAufgegebenLayout);
             pnlAufgegebenLayout.setHorizontalGroup(
                 pnlAufgegebenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                 .addGroup(pnlAufgegebenLayout.createSequentialGroup()
                     .addContainerGap()
                     .addGroup(pnlAufgegebenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                         .addComponent(scrAufgegeben, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                         .addComponent(lblAufgegeben))
                     .addContainerGap())
             );
             pnlAufgegebenLayout.setVerticalGroup(
                 pnlAufgegebenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                 .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAufgegebenLayout.createSequentialGroup()
                     .addContainerGap()
                     .addComponent(lblAufgegeben)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(scrAufgegeben, javax.swing.GroupLayout.DEFAULT_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addContainerGap())
             );
             
        pnlTab.addTab("Aufgegeben", pnlAufgegeben); // NOI18N

        btnZuruecksetzen.setText("Zurücksetzen"); // NOI18N
        btnZuruecksetzen.setName("btnZuruecksetzen"); // NOI18N
        btnZuruecksetzen.addActionListener(this);
        btnZuruecksetzen.setActionCommand("reset");

        lblTitel.setText("Spielstatistiken"); // NOI18N
        lblTitel.setName("lblTitel"); // NOI18N
        lblTitel.setFont(new java.awt.Font(this.getFont().getFontName(),0,30));

        btnZurueck.setText("Zurück"); // NOI18N
        btnZurueck.setName("btnZurueck"); // NOI18N
        btnZurueck.addActionListener(main);
        btnZurueck.setActionCommand("Zum_Hauptmenue");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                        .addComponent(btnZuruecksetzen, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnZurueck, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                    .addComponent(pnlTab, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE))
                .addContainerGap(20,20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(0,20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, 50)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnZurueck, 50, 50, 50)
                        .addComponent(btnZuruecksetzen, 50, 50, 50)))
                        .addGap(20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlTab, javax.swing.GroupLayout.DEFAULT_SIZE, 400, 450)
                .addContainerGap(20,20))
        );
    }// </editor-fold>
    
    public void stateChanged(ChangeEvent e)
    {
    	String[][] ausgabe = new String[daten.gibAnzahlEintraege()][8];
    	int tab = pnlTab.getSelectedIndex();
    	for(int j=0;j<4;j++)
    	{
    		daten.sortiereNach(tab, j);
    		for(int i=0;daten.naechsterEintragMoeglich(j) && i<ausgabe.length;i++)
    		{
    			ausgabe[i][j*2] = daten.gibNamen();
    			if(tab == 2)
    			{
    				ausgabe[i][(j*2)+1] = druckeProzent(daten.gibWert(tab, j));
    			}
    			else
    			{
    				ausgabe[i][(j*2)+1] = daten.gibWert(tab, j) + "";
    			}
    			daten.naechsterEintrag();
    		}
    	}
    	String[] spaltenBezeichnungen = new String[8]; 
    	for(int i=0;i<8;i=i+2)
    	{
    		spaltenBezeichnungen[i] = "Name";
    	}
    	if(tab == 2)
    	{
    		for(int i=1;i<8;i=i+2)
        	{
        		spaltenBezeichnungen[i] = "Prozent";
        	}
    	}
    	else
    	{
    		for(int i=1;i<8;i=i+2)
        	{
        		spaltenBezeichnungen[i] = "Anzahl";
        	}
    	}
    	JTable tabelle = null;
    	switch(tab)
    	{
    		case 0 : tabelle = tblSpiele; break;
    		case 1 : tabelle = tblSiege; break;
    		case 2 : tabelle = tblGewonnen; break;
    		case 3 : tabelle = tblAufgegeben; break;
    	}
    	tabelle.setModel(new javax.swing.table.DefaultTableModel(ausgabe,spaltenBezeichnungen));
    }
    
    private String druckeProzent(int raw)
    {
    	String output = "";
    	if(raw/1000 > 0)
    	{
    		output += (raw/1000);
    	}
    	else
    	{
    		output += " ";
    	}
    	output += (raw/100)%10 + ",";
    	if(raw%100 < 10)
    	{
    		output += "0";
    	}
    	output += (raw%100) + "%";
    	return output;
    }
    
    private void lade()
    {
    	try
    	{
    		daten = go.Statistik.gibStatistik();
    	}
    	catch (StatistikException e)
    	{
    		//Fehler abfangen
    	}
    }
    
    public void actionPerformed(ActionEvent e)
    {
    	if(e.getActionCommand().equals("reset"))
    	{
    		int antwort = JOptionPane.showConfirmDialog(this,
					"Wollen Sie die Statistik wirklich zurücksetzen?",
					"Statistik zurücksetzen", JOptionPane.YES_NO_OPTION);
    		if(antwort == 0)
    		{
    			daten.setzeZurueck();
    			stateChanged(null);
    		}
    	}
    }


    // Variables declaration - do not modify
    private javax.swing.JButton btnZurueck;
    private javax.swing.JButton btnZuruecksetzen;
    private javax.swing.JLabel lblAufgegeben;
    private javax.swing.JLabel lblGewonnen;
    private javax.swing.JLabel lblSiege;
    private javax.swing.JLabel lblSpiele;
    private javax.swing.JLabel lblTitel;
    private javax.swing.JPanel pnlAufgegeben;
    private javax.swing.JPanel pnlGewonnen;
    private javax.swing.JPanel pnlSiege;
    private javax.swing.JPanel pnlSpiele;
    private javax.swing.JTabbedPane pnlTab;
    private javax.swing.JScrollPane scrAufgegeben;
    private javax.swing.JTable tblAufgegeben;
    private javax.swing.JScrollPane scrGewonnen;
    private javax.swing.JTable tblGewonnen;
    private javax.swing.JScrollPane scrSiege;
    private javax.swing.JTable tblSiege;
    private javax.swing.JScrollPane scrSpiele;
    private javax.swing.JTable tblSpiele;
    // End of variables declaration

}
